from github_skills import (
    I_HAVE_COMPLETED_RESOLVE_MERGE_CONFLICTS,
    URL_TO_MY_COMPLETED_RESOLVE_MERGE_CONFLICTS_REPO,   
    I_HAVE_COMPLETED_REVIEW_PULL_REQUESTS,
    URL_TO_MY_COMPLETED_REVIEW_PULL_REQUESTS_REPO,
)


def test_resolve_merge_conflicts():
    assert I_HAVE_COMPLETED_RESOLVE_MERGE_CONFLICTS
    assert URL_TO_MY_COMPLETED_RESOLVE_MERGE_CONFLICTS_REPO != ""


def test_review_pull_requests():
    assert I_HAVE_COMPLETED_REVIEW_PULL_REQUESTS
    assert URL_TO_MY_COMPLETED_REVIEW_PULL_REQUESTS_REPO != ""

